// Generated by CoffeeScript 1.12.7

/*
00000000  00000000   00000000    0000000   00000000   
000       000   000  000   000  000   000  000   000  
0000000   0000000    0000000    000   000  0000000    
000       000   000  000   000  000   000  000   000  
00000000  000   000  000   000   0000000   000   000
 */

(function() {
  var error, log, post, ref, str;

  ref = require('./kxk'), log = ref.log, str = ref.str, post = ref.post;

  error = function() {
    var s;
    s = '[ERROR] ' + ((function() {
      var i, len, ref1, results;
      ref1 = [].slice.call(arguments, 0);
      results = [];
      for (i = 0, len = ref1.length; i < len; i++) {
        s = ref1[i];
        results.push(str(s));
      }
      return results;
    }).apply(this, arguments)).join(" ");
    console.error(s);
    return log.slog(s);
  };

  module.exports = error;

}).call(this);
