// Generated by CoffeeScript 1.12.7

/*
 0000000  000000000   0000000   000000000  00000000  
000          000     000   000     000     000       
0000000      000     000000000     000     0000000   
     000     000     000   000     000     000       
0000000      000     000   000     000     00000000
 */

(function() {
  var State, error, log, ref, store;

  ref = require('./kxk'), store = ref.store, error = ref.error, log = ref.log;

  State = (function() {
    function State() {}

    State.store = null;

    State.init = function() {
      if (this.store != null) {
        return error('State.init -- duplicate stores?');
      }
      return this.store = new store('state', {
        separator: '|'
      });
    };

    State.get = function(key, value) {
      return this.store.get(key, value);
    };

    State.set = function(key, value) {
      return this.store.set(key, value);
    };

    State.del = function(key, value) {
      return this.store.del(key);
    };

    State.save = function() {
      return this.store.save();
    };

    return State;

  })();

  module.exports = State;

}).call(this);
